### ISSUE TITLE
Remove old worker endpoint if pod was rescheduled

### ISSUE THREAD

**Issue by r7vme** [giantswarm/kvm-operator#134]
After recreating all my workers i have following ips for `kubectl get ep/worker -n XXX -o yaml`. Cluster has only 3 workers.

```
subsets:
- addresses:
  - ip: 172.23.0.130
  - ip: 172.23.0.246
  - ip: 172.23.0.90
  - ip: 172.23.0.94
  - ip: 172.23.1.114
  - ip: 172.23.1.158
  - ip: 172.23.1.94
```
